config/routes.rb
Rails.application.routes.draw do
  get 'session/omniauth'

  root to: 'static#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  
  resources :users, only: [:show, :edit, :update, :destroy], path: :profile

  resources :studios do
    resources :recording_sessions, only: [:new, :create, :show, :edit, :update], path: :recordingsessions
  end #:show :edit and :update

  resources :recording_sessions, only: [:index, :destroy], path: :recordingsessions do
    get 'thisweek', on: :collection
  end
end

app/models/recording_session.rb
class RecordingSession < ApplicationRecord
  belongs_to :studio
  belongs_to :client
  has_one :user, through: :studio
  validates_presence_of :start_date, :hours_per_day, :per_hour
  accepts_nested_attributes_for :client

  scope :this_week, -> { where(start_date: Time.now..7.days.from_now) }

  def client_attributes=(attributes)
    if !attributes[:id].blank?
      # byebug
      client = Client.find_by(id: attributes[:id])
      client.update(attributes)
    else
      self.client = Client.find_or_create_by(attributes)
    end
  end
  
  def days_available_by_budget
    client.budget / (hours_per_day * per_hour)
  end

  def end_date
    start_date + days_available_by_budget
  end
end

app/models/recordingsession.rb
# create_table "recordingsessions", force: :cascade do |t|
#   t.integer "studio_id", null: false
#   t.integer "client_id", null: false
#   t.date "start_date"
#   t.date "end_date"
#   t.integer "hours_per_day"
#   t.integer "per_hour"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
#   t.index ["client_id"], name: "index_recordingsessions_on_client_id"
#   t.index ["studio_id"], name: "index_recordingsessions_on_studio_id"
# end



class Recordingsession < ApplicationRecord
  belongs_to :studio
  belongs_to :client
  validates_presence_of :start_date, :end_date, :hours_per_day, :per_hour
end

app/controllers/recording_sessions_controller.rb
class RecordingSessionsController < ApplicationController
  before_action :require_login
  before_action :set_studio, only: %i[new create show edit update]
  before_action :set_recordingsession, except: %i[new create index thisweek]
  before_action :check_user, only: %i[show edit]
  
  def index
    @studios = current_user.studios
    @recordingsessions = current_user.recording_sessions
  end

  def new
    @recordingsession = RecordingSession.new
    @recordingsession.build_client
  end

  def create
    @recordingsession = RecordingSession.new(recordingsession_params)
    if @recordingsession.valid?
      @recordingsession.save
      redirect_to studio_recording_session_path(@recordingsession.studio, @recordingsession)
    else
      flash[:alert] = 'Make sure to fill out all fields.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    # byebug
    @recordingsession.update(recordingsession_params)
    if @recordingsession.valid?
      flash[:notice] = 'Session Sucessfully Updated'
      redirect_to studio_recording_session_path(@recordingsession.studio, @recordingsession)
    else
      flash[:notice] = 'Invalid Update'
      render :edit
    end
  end

  def destroy
    @recordingsession.destroy
    redirect_to recording_sessions_path
  end

  def thisweek
    @recordingsessions = current_user.recording_sessions.this_week
    render 'recording_sessions/index'
  end

  private

  def recordingsession_params
    params.require(:recording_session).permit(
      :id,
      :studio_id,
      :start_date,
      :hours_per_day,
      :per_hour,
      client_attributes: [:id, :name, :email, :genre, :budget, :band, :drums]
    )
  end

  def set_recordingsession
    @recordingsession = RecordingSession.find(params[:id])
  end

  def set_studio
    @studio = Studio.find(params[:studio_id])
  end

  def check_user
    if current_user != @recordingsession.user
      flash[:notice] = "That isn't your session!"
      redirect_to studios_path
    end
  end
end

app/controllers/recordingsessions_controller.rb
class RecordingsessionsController < ApplicationController
  before_action :set_recordingsession, except: [:new, :create]
  def index
  end

  def new
    # byebug
    if params[:studio_id] && (@studio = Studio.find_by_id(params[:studio_id]))
      @recordingsession = @studio.recordingsessions.build
      @client = @recordingsession.build_client
      render 'recordingsessions/new'
    end
  end

  def create
    recordingsession = Recordingsession.new(recordingsession_params)
    byebug
    if recordingsession.valid?
      recordingsession.save
      redirect_to '/'
    else
      flash[:alert] = "Make sure to fill out all fields."
      render :new
    end
  end

  def show 
  end

  def edit
  end
  
  def update

  end

  def destroy

  end

  private

  def recordingsession_params
  end

  def set_recordingsession
    @recordingsession = Recordingsession.find(params[:id])
  end
end

app/helpers/recording_sessions_helper.rb
module RecordingSessionsHelper
  def hours_per_day_helper(session)
    pluralize(session.hours_per_day, 'hour')
  end

  def index_header_sessions
    if params[:action] == 'thisweek'
      "This Week's Sessions"
    else
      'Your Sessions'
    end
  end

  def days_available_helper(session)
    pluralize(session.days_available_by_budget, "day")
  end

  def submit_form_helper
    if params[:action] == 'edit'
      'Edit Session'
    else
      'Create Session'
    end
  end
end

app/views/recording_sessions/_form.html.erb
<%= render partial: "layouts/error", locals: { object: @recordingsession } %>

<%= bootstrap_form_for([@studio, @recordingsession]) do |f| %>
<%= f.alert_message "Please fix the errors below." %>
<%= f.hidden_field :studio_id, value: @studio.id %>
<%= f.date_field :start_date, label: "Start Date", required: true %></br>
<%= f.number_field :hours_per_day, label: "Hours Per Day", required: true %></br>
<%= f.number_field :per_hour, label: "Per Hour", prepend: "$", append: ".00", required: true%> </br>
<%= render partial: "clients/client_fields", locals: {f: f} %>
<%= f.primary submit_form_helper %>
<% end %>

app/views/recording_sessions/edit.html.erb
<%= render partial: "layouts/error", locals: { object: @recordingsession } %>

<%= render partial: "form" %>

app/views/recording_sessions/index.html.erb
<div class= "page-header">
<h1 class= "text-center"> <%= index_header_sessions %> </h1>
<p class= "text-center text-muted font-weight-light"> view and edit your sessions </p> 
</div>
<hr>
 <br>
 <div class="row text-center">
<% @recordingsessions.each do |session| %>

  <div class="card mx-auto" style="width: 18rem;">
    <div class="card-body">
    <h5 class="card-title"><%= link_to "Session at #{session.studio.name} with #{session.client.name} on #{session.start_date}", studio_recording_session_path(session.studio, session) %></h5>
    <p class="card-text">Session is located at <%= studio_address_helper(session.studio) %> </p>
    <div class = "btn-group">
      <%= button_to 'Edit Session', edit_studio_recording_session_path(session.studio, session), method: :get, class: 'btn btn-primary'%> <%= button_to 'Delete Session', recording_session_path(session), method: :delete, :onclick => "return confirm('Are you sure you want to delete this session?')", class: "btn btn-danger"%>
    </div>
    </div>
  </div>
<% end %>
</div>

app/views/recording_sessions/new.html.erb
<h1 class= "text-center" > Create New Session At <%= @studio.name %> </h1>

<%= render partial: "form" %>

app/views/recording_sessions/show.html.erb
<div class= "page-header">
<h1 class= "text-center"> Your Session </h1>
<p class= "text-center text-muted font-weight-light"> with <%= @recordingsession.client.name %> on <%= @recordingsession.start_date%>. </p> 
</div>
</br>
<h5 class="text-center"> Studio Information </h5>
</br>
<%= render partial: "studios/studio_info" %>

</br>
<h5 class="text-center">Session Information</h5>
</br>
  <ul class= "list-group">
<li class="list-group-item">Your client, <%= @recordingsession.client.name %>, is a <%= @recordingsession.client.genre%> artist. </li>
<li class="list-group-item">You're charging the client <%=number_to_currency(@recordingsession.per_hour)%> per hour for <%= hours_per_day_helper(@recordingsession) %> a day. </li>
<li class="list-group-item">Given their budget is <%= number_to_currency(@recordingsession.client.budget) %>, they have <%= days_available_helper(@recordingsession) %> for their session. </li>
<li class="list-group-item">If that doesn't seem right, you can email <%= @recordingsession.client.name %> at <%= @recordingsession.client.email %>.</li>
<li class="list-group-item">The session starts on <%= @recordingsession.start_date %> and is currently scheduled to end at <%= @recordingsession.end_date %>.</li>
</br>
<h5 class= "text-center"> Client Details </h5>
</br>
<%= band_helper(@recordingsession.client) %>
<%= drums_helper(@recordingsession.client) %>
  </p>
    </div>
  </div>

<br>
<div class="btn-group mx-auto">
<%= button_to 'Edit Session', edit_studio_recording_session_path(@studio, @recordingsession), method: :get, class: 'btn btn-primary mx-auto'%> 
<%= button_to 'Delete Session', recording_session_path(@recordingsession), method: :delete, :onclick => "return confirm('Are you sure you want to delete this session?')", class: "btn btn-danger"%>
</div>