config/routes.rb
Rails.application.routes.draw do
  get 'session/omniauth'

  root to: 'static#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'
  
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  
  resources :users, only: [:show, :edit, :update, :destroy], path: :profile

  resources :studios do
    resources :recording_sessions, only: [:new, :create, :show, :edit, :update], path: :recordingsessions
  end #:show :edit and :update

  resources :recording_sessions, only: [:index, :destroy], path: :recordingsessions do
    get 'thisweek', on: :collection
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :recording_sessions, dependent: :destroy
  has_many :clients, through: :recording_sessions
  belongs_to :user
  validates_presence_of :name, :address_line_1, :city, :state, :zip_code, :daw, :rental_cost
  validates :email, presence: true, uniqueness: true
  before_save :capitalize_attributes

  def capitalize_attributes
    self.attributes.each do |attr,val|
      self.send("#{attr}=",val.strip.titleize) if self.capitalizable_attributes.include?(attr) && !val.nil?
    end
  end


  def capitalizable_attributes
    %w[name address_line_1 city state daw]
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :require_login
  before_action :set_studio, except: [:new, :create, :index]
  before_action :check_user, only: [:show, :edit]

  def index
    @studios = current_user.studios
  end

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.user_id = session[:user_id]
    if @studio.valid?
      @studio.save
      redirect_to studios_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @studio.update(studio_params)
    if @studio.valid?
      flash[:notice] = 'Studio Sucessfully Updated'
      redirect_to studio_path(@studio)
    else
      flash[:notice] = 'Invalid Update'
      render :edit
    end
  end

  def destroy
    @studio.destroy
    redirect_to studios_path
  end

  private

  def studio_params
    
    params.require(:studio).permit(
      :name,
      :email,
      :description,
      :address_line_1,
      :address_line_2,
      :city,
      :state,
      :zip_code,
      :user_id,
      :daw,
      :rental_cost
    )
  end

  def set_studio
    @studio = Studio.find(params[:id])
  end

  def check_user
    if current_user != @studio.user
      flash[:notice] = "That isn't your studio!"
      redirect_to studios_path
    end
  end
end

app/helpers/studios_helper.rb
module StudiosHelper
  def li_rental_cost_helper(studio)
    if studio.rental_cost.zero?
      content_tag(:li, 'Rental Cost: Free', class: "list-group-item")
    else
      content_tag(:li, "Rental Cost: #{number_to_currency(studio.rental_cost)}", class: "list-group-item")
    end
  end

  def li_description_helper(studio)
    if !studio.description.blank?
      content_tag(:li,"Description: #{studio.description.to_s}", class: "list-group-item")
    else
      content_tag(:li, "No Description Provided", class: "list-group-item disabled")
    end
  end

  def studio_address_helper(studio)
    content_tag(
      :div,
      "#{studio.address_line_1}, #{studio.address_line_2} #{studio.city}, #{studio.state}, #{studio.zip_code}"
    )
  end

  def us_states
    [
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
    ]
  end
end

app/views/studios/_form.html.erb
<%= bootstrap_form_for(@studio) do |f| %>
<%= f.form_group do %>
<%= f.text_field :name, label: "Studio Name", required: true %>
<%= f.text_field :email, required: true %>
<% end %>
</br>
</br>
<%= f.form_group do %>
<%= f.text_field :address_line_1, label: "Street Address", required: true %>
<%= f.text_field :city, required: true %>
<%= f.select :state, options_for_select(us_states, @studio.state), include_blank: true, required: true  %>
<%= f.text_field :zip_code, label: "Zip Code", required: true %>
<% end %>
</br>
</br>
<%= f.text_field :daw, label: "DAW", required: true  %>
<%= f.number_field :rental_cost, label: "Rental Cost", label_class: "label-primary", prepend: "$", append:".00", required: true %>
</br>
<%= f.text_area :description%>
</br>
<%= f.primary %>
<% end %>

app/views/studios/_studio_info.html.erb
 <div class="mx-auto">
  <ul class="list-group card-text">
    <li class="list-group-item"> Email:  <%= @studio.email %> </li> 
    <li class="list-group-item"> Address: <%= studio_address_helper(@studio) %> </li> 
    <li class="list-group-item">DAW:  <%= @studio.daw %> </li> 
    <%= li_rental_cost_helper(@studio) %> </li>
    <%= li_description_helper(@studio) %> </li>
  </ul>
</div>

app/views/studios/edit.html.erb
<h1 class= "text-center">Edit <%= @studio.name %> </h1>

<%# <%= render partial: "layouts/error", locals: { object: @studio } %>
<%# Above is commented out because of the error inline messages generated below %>

<%= render partial: 'form' %>

app/views/studios/index.html.erb
<div class= "page-header">
<h1 class= "text-center"> My Studios </h1>
<p class= "text-center text-muted font-weight-light"> view, edit, and create recording sessions </p> 
</div>
 <div class="row text-center">
 
<% @studios.each do |studio| %>

  <div class="card mx-auto">
    <div class="card-body">
    <h5 class="card-title"><%= link_to studio.name, studio_path(studio) %> </h5>
    <p class="card-text"><%= studio_address_helper(studio) %> </p>
    <div class = "btn-group">
      <%= button_to 'Edit Studio', edit_studio_path(studio), method: :get, class: 'btn btn-primary'%> 
      <%= button_to 'Delete Studio', studio_path(studio), method: :delete, :onclick => "return confirm('Deleting this studio will also delete all of its sessions. Are you sure?')", class: "btn btn-danger"%>
    </div>
    <br>
    <br>
    <%= button_to 'Create New Session', new_studio_recording_session_path(studio), method: :get, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>
</div>
<br>
<div class = "text-center">
 <%= button_to 'Create New Studio', new_studio_path, method: :get, class: 'text-center btn btn-primary'%>
 </div>

app/views/studios/new.html.erb
<h1 class= "text-center">Create New Studio</h1>

<%# <%= render partial: "layouts/error", locals: { object: @studio } %>
<%# Above is commented out because of the error inline messages generated below %>

<%= render partial: 'form' %>

app/views/studios/show.html.erb
<h1 class="text-center"> <%= @studio.name %> </h1>
 
<%= render partial: "studio_info" %>

<br>
 <div class = "btn-group mx-auto text-center">
    <%= button_to 'Edit Studio', edit_studio_path(@studio), method: :get, class: 'btn btn-primary'%> 
    <%= button_to 'Delete Studio', studio_path(@studio), method: :delete, :onclick => "return confirm('Deleting this studio will also delete all of its sessions. Are you sure?')", class: "btn btn-danger"%>
  </div>